# Generated by Django 5.1.1 on 2024-10-01 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CausaMotivo',
            fields=[
                ('codigo', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'CausaMotivo',
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('codigo', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('codigo_pais', models.CharField(max_length=3)),
                ('nombre_departamento', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'Departamento',
            },
        ),
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('codigo', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=300, null=True)),
                ('codigo_padre', models.CharField(blank=True, max_length=4, null=True)),
            ],
            options={
                'db_table': 'Diagnostico',
            },
        ),
        migrations.CreateModel(
            name='Discapacidad',
            fields=[
                ('codigo', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'Discapacidad',
            },
        ),
        migrations.CreateModel(
            name='Entidad',
            fields=[
                ('codigo', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'Entidad',
            },
        ),
        migrations.CreateModel(
            name='Etnia',
            fields=[
                ('codigo', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'Etnia',
            },
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('codigo', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'db_table': 'Genero',
            },
        ),
        migrations.CreateModel(
            name='ModalidadRealizacion',
            fields=[
                ('codigo', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'ModalidadRealizacion',
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('codigo', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('codigo_departamento', models.CharField(max_length=5)),
                ('nombre', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'Municipio',
            },
        ),
        migrations.CreateModel(
            name='Ocupacion',
            fields=[
                ('codigo', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=200, null=True)),
                ('codigo_padre', models.CharField(blank=True, max_length=4, null=True)),
            ],
            options={
                'db_table': 'Ocupacion',
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('codigo', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'Pais',
            },
        ),
        migrations.CreateModel(
            name='Sexo',
            fields=[
                ('codigo', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'Sexo',
            },
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('codigo', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'TipoDocumento',
            },
        ),
        migrations.CreateModel(
            name='ViaIngreso',
            fields=[
                ('codigo', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'ViaIngreso',
            },
        ),
        migrations.CreateModel(
            name='ZonaResidencial',
            fields=[
                ('codigo', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'ZonaResidencial',
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Identificacion', models.CharField(max_length=20)),
                ('PrimerApellido', models.CharField(max_length=50)),
                ('SegundoApellido', models.CharField(blank=True, max_length=50, null=True)),
                ('PrimerNombre', models.CharField(max_length=50)),
                ('SegundoNombre', models.CharField(blank=True, max_length=50, null=True)),
                ('FechaNacimiento', models.DateField()),
                ('HoraNacimiento', models.TimeField(blank=True, null=True)),
                ('CodigoEntidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medvisit.entidad')),
                ('CodigoEtnia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medvisit.etnia')),
                ('CodigoGenero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medvisit.genero')),
                ('CodigoMunicipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medvisit.municipio')),
                ('CodigoOcupacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medvisit.ocupacion')),
                ('CodigoPaisResidencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medvisit.pais')),
                ('CodigoSexo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medvisit.sexo')),
                ('CodigoTipoDocumento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medvisit.tipodocumento')),
                ('CodigoZonaResidencial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medvisit.zonaresidencial')),
            ],
        ),
        migrations.CreateModel(
            name='VoluntadAnticipada',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('voluntad', models.CharField(blank=True, max_length=2, null=True)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('codigo_prestador', models.CharField(blank=True, max_length=12, null=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medvisit.paciente')),
            ],
            options={
                'db_table': 'VoluntadAnticipada',
            },
        ),
        migrations.CreateModel(
            name='Oposicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manifestacion', models.CharField(max_length=2)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medvisit.paciente')),
            ],
            options={
                'db_table': 'Oposicion',
                'unique_together': {('paciente', 'manifestacion')},
            },
        ),
        migrations.CreateModel(
            name='PacienteDiagnostico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnostico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medvisit.diagnostico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medvisit.paciente')),
            ],
            options={
                'db_table': 'PacienteDiagnostico',
                'unique_together': {('paciente', 'diagnostico')},
            },
        ),
        migrations.CreateModel(
            name='PacienteDiscapacidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discapacidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medvisit.discapacidad')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medvisit.paciente')),
            ],
            options={
                'db_table': 'PacienteDiscapacidad',
                'unique_together': {('paciente', 'discapacidad')},
            },
        ),
        migrations.CreateModel(
            name='PacienteNacionalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medvisit.paciente')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medvisit.pais')),
            ],
            options={
                'db_table': 'PacienteNacionalidad',
                'unique_together': {('paciente', 'pais')},
            },
        ),
    ]
