# Generated by Django 5.1.1 on 2024-10-01 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medvisit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicioSalud',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('CodigoPrestadoServicio', models.CharField(max_length=100)),
                ('FechaHoraAtencion', models.DateTimeField()),
                ('CodigoGrupoServicio', models.CharField(choices=[('01', 'Consulta externa'), ('02', 'Apoyo diagnostico y complementacion terapeutica'), ('03', 'Internación'), ('04', 'Quirurgico'), ('05', 'Atencion Inmediata')], max_length=100)),
                ('CodigoEntorno', models.CharField(choices=[('01', 'Hogar'), ('02', 'Comunitario'), ('03', 'Escolar'), ('04', 'Laboral'), ('05', 'Institucional')], max_length=100)),
                ('ClasificacionTriage', models.CharField(choices=[('01', 'Triage I'), ('02', 'Triage II'), ('03', 'Triage III'), ('04', 'Triage IV'), ('05', 'Triage V')], max_length=100)),
                ('TipoDiagnosticoPrincipal', models.CharField(choices=[('01', 'Impresión diagnostica'), ('02', 'Confirmado nuevo'), ('03', 'Confirmado repetido')], max_length=100)),
                ('CodigoCausaMotivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medvisit.causamotivo')),
                ('CodigoDiagnostico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medvisit.diagnostico')),
                ('CodigoModalidadRealizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medvisit.modalidadrealizacion')),
                ('CodigoViaIngreso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medvisit.viaingreso')),
                ('IdPaciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medvisit.paciente')),
            ],
        ),
    ]
