# Generated by Django 5.1.1 on 2024-10-02 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medvisit', '0002_serviciosalud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genero',
            name='codigo',
            field=models.CharField(max_length=2, primary_key=True, serialize=False, unique=True),
        ),
    ]
