# Generated by Django 5.1.1 on 2024-10-02 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medvisit', '0004_alter_genero_codigo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Generos',
            fields=[
                ('codigo', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'db_table': 'Generos',
            },
        ),
    ]
