# Generated by Django 5.1.1 on 2024-10-02 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medvisit', '0005_generos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Generos',
        ),
    ]
