# Generated by Django 5.1.1 on 2024-10-02 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medvisit', '0006_delete_generos'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='serviciosalud',
            table='Paciente',
        ),
    ]
