# Generated by Django 5.1.1 on 2024-10-02 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medvisit', '0007_alter_serviciosalud_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='serviciosalud',
            table=None,
        ),
    ]
