# Generated by Django 5.1.1 on 2024-10-02 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medvisit', '0009_alter_paciente_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='paciente',
            table=None,
        ),
    ]
