# Generated by Django 5.1.1 on 2024-10-02 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medvisit', '0010_alter_paciente_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='paciente',
            table='Paciente',
        ),
        migrations.AlterModelTable(
            name='serviciosalud',
            table='ServicioSalud',
        ),
    ]
