# Generated by Django 5.1.1 on 2024-10-24 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medvisit', '0011_alter_paciente_table_alter_serviciosalud_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PacienteDiagnostico',
        ),
    ]
